service: nest-serverless-example

plugins:
  - serverless-offline

custom:
  serverless-offline:
    noPrependStageInUrl: true

provider:
  name: aws
  deploymentMethod: direct
  stage: prod
  region: ca-central-1
  runtime: nodejs14.x

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: ANY
          path: '/'
      - http:
          method: ANY
          path: '{proxy+}'