export default [
  {
    priority: 'high',
    applicantId: 3,
    id: 1,
    submittedDate: '2022-01-05',
    status: 'active',
    subStatus: 'sub-status',
    assigneeId: 4,
  },
  {
    priority: 'critical',
    applicantId: 7,
    id: 2,
    submittedDate: '2022-02-10',
    status: 'fulfillment',
    subStatus: 'sub-status',
    assigneeId: 9,
  },
  {
    priority: 'low',
    applicantId: 1,
    id: 3,
    submittedDate: '2022-03-15',
    status: 'cancelled',
    subStatus: 'sub-status',
    assigneeId: 6,
  },
  {
    priority: 'highest',
    applicantId: 5,
    id: 4,
    submittedDate: '2022-04-20',
    status: 'fraud',
    subStatus: 'sub-status',
    assigneeId: 12,
  },
  {
    priority: 'minor',
    applicantId: 12,
    id: 5,
    submittedDate: '2022-05-25',
    status: 'complete',
    subStatus: 'sub-status',
    assigneeId: 2,
  },
  {
    priority: 'major',
    applicantId: 6,
    id: 6,
    submittedDate: '2022-06-30',
    status: 'active',
    subStatus: 'sub-status',
    assigneeId: 15,
  },
  {
    priority: 'trivial',
    applicantId: 11,
    id: 7,
    submittedDate: '2022-07-05',
    status: 'fulfillment',
    subStatus: 'sub-status',
    assigneeId: 1,
  },
  {
    priority: 'medium',
    applicantId: 4,
    id: 8,
    submittedDate: '2022-08-10',
    status: 'cancelled',
    subStatus: 'sub-status',
    assigneeId: 8,
  },
  {
    priority: 'blocker',
    applicantId: 2,
    id: 9,
    submittedDate: '2022-09-15',
    status: 'active',
    subStatus: 'sub-status',
    assigneeId: 11,
  },
  {
    priority: 'highest',
    applicantId: 14,
    id: 10,
    submittedDate: '2022-10-20',
    status: 'complete',
    subStatus: 'sub-status',
    assigneeId: 3,
  },
  {
    priority: 'major',
    applicantId: 9,
    id: 11,
    submittedDate: '2022-11-25',
    status: 'fraud',
    subStatus: 'sub-status',
    assigneeId: 10,
  },
  {
    priority: 'low',
    applicantId: 8,
    id: 12,
    submittedDate: '2022-11-25',
    status: 'fulfillment',
    subStatus: 'sub-status',
    assigneeId: 7,
  },
  {
    priority: 'highest',
    applicantId: 13,
    id: 13,
    submittedDate: '2023-01-05',
    status: 'active',
    subStatus: 'sub-status',
    assigneeId: 2,
  },
  {
    priority: 'trivial',
    applicantId: 10,
    id: 14,
    submittedDate: '2023-02-10',
    status: 'cancelled',
    subStatus: 'sub-status',
    assigneeId: 9,
  },
  {
    priority: 'medium',
    applicantId: 1,
    id: 15,
    submittedDate: '2023-03-15',
    status: 'complete',
    subStatus: 'sub-status',
    assigneeId: 6,
  },
  {
    priority: 'blocker',
    applicantId: 15,
    id: 16,
    submittedDate: '2023-04-20',
    status: 'active',
    subStatus: 'sub-status',
    assigneeId: 5,
  },
  {
    priority: 'major',
    applicantId: 7,
    id: 17,
    submittedDate: '2023-05-25',
    status: 'fulfillment',
    subStatus: 'sub-status',
    assigneeId: 14,
  },
  {
    priority: 'low',
    applicantId: 11,
    id: 18,
    submittedDate: '2023-06-30',
    status: 'cancelled',
    subStatus: 'sub-status',
    assigneeId: 3,
  },
  {
    priority: 'critical',
    applicantId: 6,
    id: 19,
    submittedDate: '2023-07-05',
    status: 'active',
    subStatus: 'sub-status',
    assigneeId: 12,
  },
  {
    priority: 'highest',
    applicantId: 10,
    id: 20,
    submittedDate: '2023-08-10',
    status: 'fulfillment',
    subStatus: 'sub-status',
    assigneeId: 2,
  },
];
