export default [
  {
    id: 1,
    email: 'johndoe@example.com',
    firstName: 'John',
    lastName: 'Doe',
    avatarURL: 'https://via.placeholder.com/150',
  },
  {
    id: 2,
    email: 'janedoe@example.com',
    firstName: 'Jane',
    lastName: 'Doe',
    avatarURL: 'https://via.placeholder.com/150',
  },
  {
    id: 3,
    email: 'bobsmith@example.com',
    firstName: 'Bob',
    lastName: 'Smith',
    avatarURL: 'https://via.placeholder.com/150',
  },
  {
    id: 4,
    email: 'sarahjones@example.com',
    firstName: 'Sarah',
    lastName: 'Jones',
    avatarURL: 'https://via.placeholder.com/150',
  },
  {
    id: 5,
    email: 'mikebrown@example.com',
    firstName: 'Mike',
    lastName: 'Brown',
    avatarURL: 'https://via.placeholder.com/150',
  },
  {
    id: 6,
    email: 'amandasmith@example.com',
    firstName: 'Amanda',
    lastName: 'Smith',
    avatarURL: 'https://via.placeholder.com/150',
  },
  {
    id: 7,
    email: 'chrisjohnson@example.com',
    firstName: 'Chris',
    lastName: 'Johnson',
    avatarURL: 'https://via.placeholder.com/150',
  },
  {
    id: 8,
    email: 'lisaadams@example.com',
    firstName: 'Lisa',
    lastName: 'Adams',
    avatarURL: 'https://via.placeholder.com/150',
  },
  {
    id: 9,
    email: 'davidsmith@example.com',
    firstName: 'David',
    lastName: 'Smith',
    avatarURL: 'https://via.placeholder.com/150',
  },
  {
    id: 10,
    email: 'mariaperez@example.com',
    firstName: 'Maria',
    lastName: 'Perez',
    avatarURL: 'https://via.placeholder.com/150',
  },
  {
    id: 11,
    email: 'jessicabaker@example.com',
    firstName: 'Jessica',
    lastName: 'Baker',
    avatarURL: 'https://via.placeholder.com/150',
  },
  {
    id: 12,
    email: 'ryanlee@example.com',
    firstName: 'Ryan',
    lastName: 'Lee',
    avatarURL: 'https://via.placeholder.com/150',
  },
  {
    id: 13,
    email: 'johncarter@example.com',
    firstName: 'John',
    lastName: 'Carter',
    avatarURL: 'https://via.placeholder.com/150',
  },
  {
    id: 14,
    email: 'caroldavis@example.com',
    firstName: 'Carol',
    lastName: 'Davis',
    avatarURL: 'https://via.placeholder.com/150',
  },
];
